# Generated by Django 5.0.1 on 2024-01-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song_name',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
